version: '3.1'

services:
  
  db:
    image: postgres
    restart: always
    envirement:
      DB_USER: test
      DB_PASSWORD: test
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local


    