version: '3.8'
services:
  testdb:
    image: postgres:latest
    container_name: pingpong_db
    restart: always
    ports:
      - '5432:5432'
    envirement:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: pgdata
    driver: local