version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: pingpong_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust

  # backend:
  #   build: ./backend
  #   image: backend
  #   container_name: backend
  #   restart: unless-stopped
  #   ports:
  #     - 5000:5000
  #     - 5555:5555
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

  # frontend:
  #   build: ./frontend
  #   image: frontend
  #   container_name: frontend
  #   restart: unless-stopped
  #   ports:
  #     - 5173:5173
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend
